# Generated by Django 5.2.6 on 2026-01-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIToken',
            new_name='APIKey',
        ),
    ]
