# Generated by Django 5.2.6 on 2026-01-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credits',
            new_name='UsageCredits',
        ),
    ]
