# Generated by Django 5.2.4 on 2025-07-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomToken',
            new_name='APIToken',
        ),
    ]
