# Generated by Django 5.2.6 on 2026-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_apitoken_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicredits',
            name='credits_in_use',
        ),
        migrations.RemoveField(
            model_name='bulkcredits',
            name='credits_in_use',
        ),
        migrations.RemoveField(
            model_name='credits',
            name='credits_in_use',
        ),
        migrations.AlterField(
            model_name='apicredits',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bulkcredits',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='credits',
            name='credits',
            field=models.IntegerField(),
        ),
    ]
