# Generated by Django 5.2.6 on 2026-01-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_credits_usagecredits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsageCredits',
            new_name='Credits',
        ),
    ]
