# Generated by Django 5.2.4 on 2025-07-15 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_apicredits_bulkcredits_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 7, 26, 16, 436221, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bulkcredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 7, 26, 16, 435797, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='credits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 7, 26, 16, 435381, tzinfo=datetime.timezone.utc)),
        ),
    ]
