# Generated by Django 5.2.4 on 2025-07-18 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_apicredits_expires_alter_bulkcredits_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 12, 40, 5, 633601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bulkcredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 12, 40, 5, 633047, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='credits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 12, 40, 5, 632619, tzinfo=datetime.timezone.utc)),
        ),
    ]
