# Generated by Django 5.2.4 on 2025-07-22 09:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_apicredits_expires_alter_bulkcredits_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 34, 43, 522094, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='apicredits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulkcredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 34, 43, 521718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bulkcredits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 34, 43, 521281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='credits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
