# Generated by Django 5.2.4 on 2025-07-22 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_apicredits_expires_alter_apicredits_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 34, 58, 564505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bulkcredits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 34, 58, 564090, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='credits',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 9, 34, 58, 563701, tzinfo=datetime.timezone.utc)),
        ),
    ]
