# Generated by Django 5.2.4 on 2025-07-15 07:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_apicredits_expires_alter_bulkcredits_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True)),
                ('expires', models.DateTimeField(default=datetime.datetime(2025, 7, 15, 7, 36, 16, 437236, tzinfo=datetime.timezone.utc))),
                ('credits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bulkcredits')),
            ],
            options={
                'ordering': ['expires'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True)),
                ('expires', models.DateTimeField(default=datetime.datetime(2025, 7, 15, 7, 36, 16, 436818, tzinfo=datetime.timezone.utc))),
                ('credits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.credits')),
            ],
            options={
                'ordering': ['expires'],
            },
        ),
    ]
