# Generated by Django 5.2.6 on 2026-01-08 11:56

import django.db.models.deletion
import infer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_token', models.CharField(max_length=40, unique=True)),
                ('completion_status', models.CharField(choices=[('FAILED', 'Failed to Complete'), ('COMPLETE', 'Fully Completed')], max_length=8, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('expires', models.DateTimeField(default=infer.models.get_expiry_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_inference_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires'],
            },
        ),
        migrations.CreateModel(
            name='BulkJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_token', models.CharField(max_length=40, unique=True)),
                ('completion_status', models.CharField(choices=[('FAILED', 'Failed to Complete'), ('COMPLETE', 'Fully Completed')], max_length=8, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('expires', models.DateTimeField(default=infer.models.get_expiry_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_inference_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_token', models.CharField(max_length=40, unique=True)),
                ('completion_status', models.CharField(choices=[('FAILED', 'Failed to Complete'), ('COMPLETE', 'Fully Completed')], max_length=8, null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('expires', models.DateTimeField(default=infer.models.get_expiry_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires'],
            },
        ),
    ]
