# Generated by Django 5.2.4 on 2025-07-15 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 7, 36, 28, 49303, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 7, 36, 28, 48836, tzinfo=datetime.timezone.utc)),
        ),
    ]
