# Generated by Django 5.2.4 on 2025-07-15 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0002_alter_bulkjobs_expires_alter_jobs_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 7, 37, 28, 377703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 7, 37, 28, 377330, tzinfo=datetime.timezone.utc)),
        ),
    ]
