# Generated by Django 5.2.4 on 2025-07-18 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0003_alter_bulkjobs_expires_alter_jobs_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 12, 49, 26, 170216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 12, 49, 26, 169791, tzinfo=datetime.timezone.utc)),
        ),
    ]
