# Generated by Django 5.2.4 on 2025-07-22 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0007_alter_bulkjobs_expires_alter_jobs_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 9, 44, 58, 565471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 9, 44, 58, 565104, tzinfo=datetime.timezone.utc)),
        ),
    ]
