"""
Django settings for simple project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Config, RepositoryEnv, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Determine which file to load
# ToDo add DJANGO_ENV when running in production accordingly
ENV_FILE = ".env.production" if os.getenv("DJANGO_ENV") == "production" else ".env"

# Load the selected .env file
config = Config(RepositoryEnv(ENV_FILE))

# Now use config() instead of the global config()
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
SECRET_KEY = config("SECRET_KEY")
ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', cast=Csv())
DJANGO_ENV = config('DJANGO_ENV', default='development')

REPLICATE_API_TOKEN = config("REPLICATE_API_TOKEN")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'users',
    'infer',
    'payments',
    # other apps
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# OR allow specific origins
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    cast=lambda v: [s.strip() for s in v.split(',')],
    default=['http://localhost:5173', 'http://127.0.0.1:5173']
)

ROOT_URLCONF = 'simple.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# DRF settings for Authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Use JWT authentication
        # 'rest_framework.authentication.TokenAuthentication',  # Alternatively for simple token
    ],

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.MultiPartParser',  # To handle multipart form data (including files)
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
    ],
}


WSGI_APPLICATION = 'simple.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'simple_api_db',
        'USER': 'louiskumarmathew',
        'PASSWORD': '1234ABcd,.',
        'HOST': 'localhost',
        'PORT': '3306',
    },
}

# Timeout in case of database lock (in seconds)
DB_LOCK_WAIT_TIMEOUT = 2

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'users.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cookies related

COOKIE_SETTINGS = {
    "ACCESS_TOKEN_VALIDITY": 3600,
    "REFRESH_TOEKN_VALIDITY": 86400,
    "HTTP_ONLY": config('COOKIE_HTTP_ONLY', default=True, cast=bool),
    "SECURE_COOKIE": config('COOKIE_SECURE', default=True, cast=bool),
    "SAME_SITE": config('COOKIE_SAMESITE', default='strict'),
}

WORKER_COOKIE_SETTINGS = {
    "DOMAIN": "simple-worker.louiskumarmathew.workers.dev",
    "ACCESS_TOKEN_VALIDITY": 3600,
    "HTTP_ONLY": config('COOKIE_HTTP_ONLY', default=True, cast=bool),
    "SECURE_COOKIE": config('COOKIE_SECURE', default=True, cast=bool),
    "SAME_SITE": "None",
}