"""
Django settings for erasebg project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path
from decouple import Config, RepositoryEnv, Csv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Determine which file to load
# ToDo add DJANGO_ENV when running in production accordingly
ENV_FILE = ".env" 

if os.getenv("DJANGO_ENV") == "production":
    ENV_FILE = ".env.production" 
elif os.getenv("DJANGO_ENV") == "development":
    ENV_FILE = ".env.dev"

print(f"Using ENV_FILE: {ENV_FILE}")

# Load the selected .env file
config = Config(RepositoryEnv(ENV_FILE))

# Now use config() instead of the global config()
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
SECRET_KEY = config("SECRET_KEY")
ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', cast=Csv())
DJANGO_ENV = config('DJANGO_ENV', default='development')

# frontend url settings
FRONTEND_URL = config('FRONTEND_URL', default='https://localhost:5173')

CLOUDFLARE_WORKER_ID = config("CLOUDFLARE_WORKER_ID")
CLOUDFLARE_WORKER_SHARED_SECRET = config("CLOUDFLARE_WORKER_SHARED_SECRET")

RESEND_API_KEY = config("RESEND_API_KEY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    # local apps
    'users',
    'infer',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# csrf token related
CSRF_COOKIE_NAME     = config('CSRF_COOKIE_NAME', default='csrftoken')
CSRF_COOKIE_HTTPONLY = config('CSRF_COOKIE_HTTPONLY', default=False)      # MUST be False because JS needs to read it
CSRF_COOKIE_SECURE   = config('CSRF_COOKIE_SECURE', default=True)
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default=None)  
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())

# session cookies
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default="None")
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True)

# OR allow specific origins
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    cast=Csv(),
    default=['http://localhost:5173', 'http://127.0.0.1:5173']
)

ROOT_URLCONF = 'erasebg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erasebg.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER', default='erasebg_backend'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'TEST': {
            'NAME': config('TEST_DB_NAME'),
            'MIRROR': None,
        }
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'users.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# DRF settings for Authentication
REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": config("ANONYMOUS_THROTTLE_RATE", default="1000/day"),
        "login": config("LOGIN_THROTTLE_RATE", default="10/minute"),
        "logout": config("LOGOUT_THROTTLE_RATE", default="10/minute"),
        "signup": config("SIGNUP_THROTTLE_RATE", default="10/hour"),
        "resend_verification_email": config("RESEND_VERIFICATION_EMAIL_THROTTLE_RATE", default="1/day"),
        "email_verification": config("EMAIL_VERIFICATION_THROTTLE_RATE", default="5/hour"),
        "refresh_access_token": config("REFRESH_ACCESS_TOKEN_THROTTLE_RATE", default="15/hour"),
        "add_credits": config("ADD_CREDITS_THROTTLE_RATE", default="10/minute"),
        "add_bulk_credits": config("ADD_BULK_CREDITS_THROTTLE_RATE", default="10/minute"),
        "add_api_credits": config("ADD_API_CREDITS_THROTTLE_RATE", default="10/minute"),
        "fetch_user_details": config("FETCH_USER_DETAILS_THROTTLE_RATE", default="60/minute"),
        "update_user_details": config("UPDATE_USER_DETAILS_THROTTLE_RATE", default="10/minute"),
        "fetch_credits": config("FETCH_CREDITS", default="60/hour"),
        "fetch_bulk_credits": config("FETCH_BULK_CREDITS", default="60/hour"),
        "fetch_api_credits": config("FETCH_API_CREDITS", default="60/hour"),
        "initiate_inference_worker": config("INITIATE_INFERENCE_WORKER_THROTTLE_RATE", default="120/minute"),
        "initiate_bulk_inference_worker": config("INITIATE_BULK_INFERENCE_WORKER_THROTTLE_RATE", default="120/minute"),
        "initiate_api_inferece_worker": config("INITIATE_API_INFERENCE_WORKER_THROTTLE_RATE", default="600/minute"),
        "wrapup_inference_worker": config("WRAPUP_INFERENCE_WORKER_THROTTLE_RATE", default="120/minute"),
        "wrapup_bulk_inference_worker": config("WRAPUP_BULK_INFERENCE_WORKER_THROTTLE_RATE", default="120/minute"),
        "wrapup_api_inference_worker": config("WRAPUP_API_INFERENCE_WORKER_THROTTLE_RATE", default="600/minute"),
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        seconds=config("ACCESS_TOKEN_LIFETIME", default=900, cast=int)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        seconds=config("REFRESH_TOKEN_LIFETIME", default=604800, cast=int)
    ),
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cookies related

COOKIE_SETTINGS = {
    "DOMAIN": config("COOKIE_DOMAIN", default="localhost:5173"),
    "ACCESS_TOKEN_VALIDITY": config("ACCESS_TOKEN_VALIDITY", default=3600, cast=int),
    "REFRESH_TOKEN_VALIDITY": config("REFRESH_TOKEN_VALIDITY", default=3600, cast=int),
    "HTTP_ONLY": config('COOKIE_HTTP_ONLY', default=True, cast=bool),
    "SECURE_COOKIE": config('COOKIE_SECURE', default=True, cast=bool),
    "SAME_SITE": config('COOKIE_SAMESITE', default='strict'),
}

WORKER_COOKIE_SETTINGS = {
    # ToDo[dev, production]: change the domain accordingly
    "DOMAIN": config("WORKER_DOMAIN", default="localhost:5173"),
    "ACCESS_TOKEN_VALIDITY": config("ACCESS_TOKEN_VALIDITY", default=3600, cast=int),
    "HTTP_ONLY": config("COOKIE_HTTP_ONLY", default=True, cast=bool),
    "SECURE_COOKIE": config("COOKIE_SECURE", default=True, cast=bool),
    "SAME_SITE": config("COOKIE_SAMESITE", default="strict"),
}

# Emails
NOTIFICATIONS_EMAIL_ID = config("NOTIFICATIONS_EMAIL_ID", default="no-reply@notifications.erasebg.co")